"""empty message

Revision ID: 5d526491016a
Revises: 4284a9a0bc55
Create Date: 2021-07-17 15:18:43.872812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d526491016a'
down_revision = '4284a9a0bc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('planet', table_name='people')
    op.drop_index('planet_2', table_name='people')
    op.drop_column('people', 'planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('planet', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('planet_2', 'people', ['planet'], unique=False)
    op.create_index('planet', 'people', ['planet'], unique=False)
    # ### end Alembic commands ###
