"""empty message

Revision ID: d09a107857ba
Revises: 5a2a28ce583c
Create Date: 2021-07-23 00:55:00.057859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd09a107857ba'
down_revision = '5a2a28ce583c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'people', 'planet', ['planet_id'], ['id'])
    op.drop_constraint('planet_ibfk_1', 'planet', type_='foreignkey')
    op.drop_column('planet', 'peopleid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('peopleid', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planet_ibfk_1', 'planet', 'people', ['peopleid'], ['id'])
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'planet_id')
    # ### end Alembic commands ###
