"""empty message

Revision ID: db4eb6126014
Revises: 
Create Date: 2021-07-26 21:36:39.615455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4eb6126014'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('density', sa.String(length=120), nullable=False),
    sa.Column('gravity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('density'),
    sa.UniqueConstraint('density'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('homeworld', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.String(length=80), nullable=False),
    sa.Column('pilots', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['pilots'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id_fav', sa.Integer(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('planet_fav', sa.Integer(), nullable=True),
    sa.Column('people_fav', sa.Integer(), nullable=True),
    sa.Column('vehicles_fav', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_fav'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_fav'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['vehicles_fav'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id_fav', 'favorites')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites'], ['favorites.id_fav'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('favorites')
    op.drop_table('vehicles')
    op.drop_table('people')
    op.drop_table('planet')
    # ### end Alembic commands ###
